### PR TITLE
Hardware extensions: fixes and menu localization

### LINKED ISSUE #1485: WeDo2/micro:bit block menus need localization

### LINKED ISSUE #1505: WeDo2 motor power between 0-30ish doesn't power the motor

### LINKED ISSUE #1592: WeDo2 and EV3 should not send motor command when motor power is 0
### Expected Behavior

In the WeDo2 and EV3 extensions, when the power level for a motor is set to 0, motor commands for that motor should not be sent. The opcode function should bail out (but in cases where the block waits for some amount of time, it should still wait).

### Actual Behavior

We send motor commands with zero power, which can cause the motors to make a whining sound.

### LINKED ISSUE #1615: Prevent multiple hardware disconnect alerts
### Expected Behavior

One alert is shown when hardware peripheral disconnects.

### Actual Behavior

In some cases, two, redundant alerts display.

### Cases to Consider:

- Preventing the VM from requesting the alert twice- it should only be when the socket closes
- Preventing the alert from getting sent if we were not already connected
- What about if you connect, disconnect, connect, disconnect. Okay to see two alerts? Lets ask Carl and Kathy

### PR DESCRIPTION
**Pull request by evhan55**
### Resolves

Resolves #1592: WeDo2 and EV3 should not send motor command when motor power is 0.

Resolves #1505: WeDo2 motor power between 0-30ish doesn't power the motor.
- Sometimes the WeDo2 still stalls at low numbers (no repro available), might be a separate issue?

Resolves #1485: WeDo2/micro:bit block menus need localization
- micro:bit menus were already localized, but I refactored the menu names to include the extension name to match other hardware extensions

Resolves #1615: Prevent multiple hardware disconnect alerts
- multiple alerts no longer show, but #1638 still needs to be addressed

These are all meant to work with Scratch Link version no. `1.18.827.1749`

### CODE REVIEW

**Review by ericrosenbaum — APPROVED** [review]
LGTM!

File: src/extensions/scratch3_wedo2/index.js [hunk 1]
```diff
@@ -1077,28 +1093,140 @@ class Scratch3WeDo2Blocks {
...
+                        value: WeDo2MotorDirection.REVERSE
+                    }
                 ],
                 TILT_DIRECTION: [
-                    WeDo2TiltDirection.UP,
-                    WeDo2TiltDirection.DOWN,
-                    WeDo2TiltDirection.LEFT,
-                    WeDo2TiltDirection.RIGHT
+                    {
+                        text: formatMessage({
```
Comment (chrisgarrity) [inline src/extensions/scratch3_wedo2/index.js:1157]: You don't need two separate message ids for 'up', 'down' etc unless they are being used in very different contexts. For example, if the word 'right' is being used as the direction and also correctness.

However, there are a couple of things to note with respect to how the strings are automatically extracted. Only the first instance in the file will get 'saved', so make sure that has the description for translators. Any following messages only need the `id` and `default`.

File: src/extensions/scratch3_wedo2/index.js [hunk 2]
```diff
@@ -1077,28 +1093,140 @@ class Scratch3WeDo2Blocks {
...
-                    WeDo2TiltDirection.DOWN,
-                    WeDo2TiltDirection.LEFT,
-                    WeDo2TiltDirection.RIGHT,
-                    WeDo2TiltDirection.ANY
+                    {
+                        text: formatMessage({
+                            id: 'wedo2.tiltDirectionAny.up',
+                            default: 'up',
+                            description: 'label for up element in tilt direction any menu for LEGO WeDo 2 extension'
+                        }),
```
Comment (chrisgarrity) [inline src/extensions/scratch3_wedo2/index.js:1194]: This could reuse the `wedo2.tiltDirection.up` message:
```
formatMessage({
    id: 'wedo2.tiltDirection.up',
    default: 'up'
}),
```
It doesn't need the description because that is above.

**Review by chrisgarrity — COMMENTED** [review]
I needed to refresh my memory of the VM tools for format-message as they're a little different from the react ones used in gui. You probably don't want to define things like 'up', 'down' etc twice, so you can reuse the message id and default string everywhere after fully defining it on the first use. I used the 'up' messages as examples.

Note, due to a limitation of the automatic extraction tool only calls to formatMessage with data are extracted: 
```
formatMessage({id: 'myId', default: 'this', description: 'an example'})
```
will extract the data from the call. But
```
aMsg = {id: 'myId', default: 'this', description: 'an example'};
formatMessage(aMsg);
```
does not extract the data.

File: src/extensions/scratch3_wedo2/index.js (hunk 2 above)
Comment (evhan55) [reply src/extensions/scratch3_wedo2/index.js:1194]: thanks!

File: src/extensions/scratch3_wedo2/index.js (hunk 1 above)
Comment (evhan55) [reply src/extensions/scratch3_wedo2/index.js:1157]: Ok, makes sense, thanks!

**Review by chrisgarrity — APPROVED** [review]
Looks good!
