### PR TITLE
Fix say/think with non-string inputs

### LINKED ISSUE #817: “say” block can't accept number input
screen shot 2017-10-29 at 10 09 01 pm

### Expected Behavior
show “4” in stage

### Actual Behavior

nothing happened
### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

### PR DESCRIPTION
**Pull request by paulkaplan**
### Resolves

_What Github issue does this resolve (please include link)?_

Fixes https://github.com/LLK/scratch-gui/issues/817

### Proposed Changes

_Describe what this Pull Request does_

`String( <> )` things before say/thinking them.

### Reason for Changes

_Explain why these changes should be made_

These kinds of blocks didn't work before, now they do!

image

### CODE REVIEW

File: src/engine/blocks.js [hunk 1]
```diff
@@ -316,6 +317,14 @@ class Blocks {
                 if (variable) {
                     block.fields[args.name].value = variable.name;
                     block.fields[args.name].id = args.value;
+                } else {
```
Comment (fsih) [inline src/engine/blocks.js]: This whole variable logic is super weird, and I feel like it would be easy to miss bugs. Is it possible to change the source of this information to provide information in a cleaner way, where it always provides an ID and the value field isn't different things?

**Review by fsih — CHANGES_REQUESTED** [review]

File: src/engine/blocks.js (hunk 1 above)
Comment (paulkaplan) [reply src/engine/blocks.js]: Oh jeez sorry this is totally unrelated, didn't mean for it to be part of this PR.

**Comment by paulkaplan** [comment]
@fsih sorry about that, resubmitted with the right code.

**Review by fsih — APPROVED** [review]
