### PR TITLE
Fix BOOST whenColor hat

### LINKED ISSUE #2091: BOOST extension: "when color seen" hat not working
The "when color seen" hat does not seem to trigger at all. I know this was working at some point! maybe the code just got out of sync.  

In general, it looks like some cleanup may be needed in how color is represented in the code, to help distinguish between the numeric values reported by the sensor, the values used internally in the menu, the localized names used on the menu, and the localized names reported by the reporter.

I would also suggest renaming the `_colorBucket` data structure, since we are using a "token bucket" in the rate limiter which is quite different- this approach seems more like a sliding window? but it could just be called `_colorSamples` or `_colorArray`.

### PR DESCRIPTION
**Pull request by ericrosenbaum**
### Resolves

Resolves https://github.com/LLK/scratch-vm/issues/2091

### Proposed Changes

This is a quick fix to make the BOOST "when color seen" hat work for the options other than "any".

### Reason for Changes

This line looks like it was a typo: `return this.getColor() === color;` That definitely never worked, because `color` is the color utility object. 

The "any" option is handled separately, and seems to work.

### CODE REVIEW

**Comment by evhan55** [comment]
I tested this with the following code:

Screen Shot 2019-04-10 at 9 29 32 AM

And the following brick pattern:
IMG_20190410_093003

And the sprite would turn when seeing both `'red'` and `'yellow'` if I held the sensor about 1cm away from the bricks.  I also confirmed that those colors were being seen by monitoring the reporter, and it works!

Seems like a good fix to me!

File: src/extensions/scratch3_boost/index.js [hunk 1]
```diff
@@ -1944,7 +1944,7 @@ class Scratch3BoostBlocks {
      * @private
      */
     _isColor (args) {
-        switch (args) {
```
Comment (evhan55) [inline src/extensions/scratch3_boost/index.js:1947]: It was switching on an array of arguments before?

**Review by evhan55 — APPROVED** [review]
lgtm!

**Comment by evhan55** [comment]
Thanks @ericrosenbaum for clarification!  Also testing the non-any options seen here, with the same brick pattern as above:

Screen Shot 2019-04-10 at 9 40 07 AM
Screen Shot 2019-04-10 at 9 40 11 AM
Screen Shot 2019-04-10 at 9 40 25 AM

The first two code snippets correctly trigger when the sensor is near the red and yellow bricks, respectively!
Also, the third code snippet does not trigger at all.

Seems like the non-any options are also working well!

**Comment by evhan55** [comment]
lgtm again!

**Comment by knandersen** [comment]
Looks great! I also really like using `args` and `args.COLOR` throughout to avoid ambiguity, which is what I suspect happened when using `color`!

As @ericrosenbaum pointed out however, there's still a matter of fixing the issue mentioned here: https://github.com/LLK/scratch-vm/issues/2091#issuecomment-480844119

Should we file that as a separate issue or change this PR to only partly resolve #2091?

File: src/extensions/scratch3_boost/index.js (hunk 1 above)
Comment (ericrosenbaum) [reply src/extensions/scratch3_boost/index.js:1947]: yup, that was also breaking the "any" condition I think, which I didn't notice

**Comment by ericrosenbaum** [comment]
Thanks! I will file an issue about the problem with multiple "when color any" hats
