### PR TITLE
Fix variable xml

### LINKED ISSUE #895: Duplicating/Cloning a sprite w/sprite-specific variables throws (non-fatal) type error.
### Expected Behavior

Duplicating or cloning a sprite should copy over variables correctly.

### Actual Behavior

Variables aren't serialized correctly when cloning or duplicating a sprite so their toXML function cannot be accessed from the emitWorkspaceUpdate, causing the following TypeError:

```
raven.js:420 Uncaught TypeError: v.toXML is not a function
    at scratch-vm.js:17116
    at Array.map (<anonymous>)
    at VirtualMachine.emitWorkspaceUpdate (scratch-vm.js:17115)
    at VirtualMachine.setEditingTarget (scratch-vm.js:17031)
    at VirtualMachine.stopDrag (scratch-vm.js:17166)
    at Stage.onStopDrag (stage.jsx:250)
    at Stage.wrapper [as onStopDrag] (index.js:550)
    at Stage.onMouseUp (stage.jsx:182)
    at HTMLDocument.wrapper (index.js:550)
    at HTMLDocument.d (raven.js:416)
```
#### Additional Notes
`RenderedTarget.duplicate()` and `RenderedTarget.makeClone` both call `JSON.parse(JSON.stringify(this.variables))` which only copies the properties of the object and not the functions. A new Variable instance should be created for each variable in this.variables.

### Steps to Reproduce

Create a new Scratch 2.0 project.
Click on Sprite1, and create a new sprite-specific variable 'spriteVar'.
Load this project in 3.0. 
Duplicate Sprite1 and observe the error. There will be a new error every time you switch to the duplicated sprite.

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

### PR DESCRIPTION
**Pull request by kchadha**
### Resolves

Resolves #895 and is a replacement for #1409.

### Proposed Changes

Fix variable duplication during making a clone of a sprite or duplicating a sprite.
There are now functions for duplicating variables (and actually creating real variable objects from them so that they get serialized to XML correctly) in one of two ways:

1) The duplicated variable gets a new ID and all block fields that reference that variable in the provided blocks container get updated to use the new variable ID. This is necessary for duplicating a sprite, in which we want local variables of different sprites to have different IDs (which is necessary for those variables to have their own monitors).

2) The duplicated variable keeps the original variable's ID, and no block field update is necessary. This is required for making a clone of a sprite because sprite clones use the same blocks container as their parent sprite. Sprite clone variables cannot be monitored separately and thus do not need to have an ID separate from the original variable.

### Reason for Changes

Fixing issues where duplicating a sprite with local variables causes errors that can eventually cause the editor to crash.

### Test Coverage

Added unit tests for the new duplicate functions.

### CODE REVIEW

File: src/engine/target.js [hunk 1]
```diff
@@ -313,6 +313,56 @@ class Target extends EventEmitter {
...
+    duplicateVariable (id, optKeepOriginalId) {
+        if (this.variables.hasOwnProperty(id)) {
+            const originalVariable = this.variables[id];
+            const newVariable = new Variable(
+                optKeepOriginalId ? id : null, // conditionally keep original id or generate a new one
+                originalVariable.name,
+                originalVariable.type,
+                originalVariable.isCloud
+            );
+            newVariable.value = originalVariable.value;
```
Comment (rschamp) [inline src/engine/target.js:334]: Really, `value` isn't part of the constructor o.O?

**Review by rschamp — APPROVED** [review]
