### PR TITLE
Use bitmap skin for video preview

### LINKED ISSUE #4888: Video transparency in video sensing doesn't go all the way invisible
### Expected Behavior

Setting the video transparency to 100 using the video sensing block `set video transparency to 100` block should cause the video to be totally transparent, and not visible.

### Actual Behavior

`set video transparency block to 100` seems to make the parts of the video that are white be white and the things that are dark to be clear.  It seems to be using the brigthness channel to affect the transparency in some way.  

Transparency100videoSensingPurple

The color that you set the background to seems to matter.  This issue is not observable if you set the backdrop to white, but the contrast changes depending on what color the backdrop is.

White/Clear backdrop at 100% transparency:
transparency100videoSensingWhite

Purple backdrop at 100% transparency:
Transparency100videoSensingPurple

Here is an example project made by @ericrosenbaum to illustrate that. scratch.mit.edu/projects/314377995

It is also worth noting that less transparent video sensing makes the colors look strange.

50% transparent on white backdrop:
Screen Shot 2019-06-04 at 11 35 38 AM

50% transparent on purple backdrop:
Transparency50videoSensingPurple

### Steps to Reproduce

Create a new project
Add the video sensing extension
Turn video on
Note: the colors in the video look a little desaturated
Drag out a `Set video transparency block to ` block out
Set the value to 100 and run the block
Note: the video appears to disappear
Add a backdrop, it's easy to see if it is a solid color
Note: the video on the stage is still visible.

### Operating System and Browser

Mac Chrome, Mac Safari

### PR DESCRIPTION
**Pull request by paulkaplan**
### Resolves

_What Github issue does this resolve (please include link)?_

Resolves LLK/scratch-gui#4888

### Proposed Changes

_Describe what this Pull Request does_

Use the BitmapSkin type for the video layer instead of the PenSkin, because the PenSkin cannot have the ghost effect applied to it due to using premultiplied alpha blending modes.

This is the solution I wanted to implement https://github.com/LLK/scratch-vm/pull/2291, but was concerned with the performance of silhouette updates. I was concerned that the bitmap skin was too slow to update because updating the silhouette required a slow canvas -> ImageData conversion. After more digging, it turns out, we are actually already doing that conversion in the video motion extension in a similarly timed loop, and so we can take advantage of the caching mechanism in the VideoProvider and request the cached ImageData. sometimes the extension loop freshens the cache, sometimes this preview updater loop does, but either way it only gets done once every 30ms, which is as good as we are going to get performance-wise since the extension requires ImageData for computation. 

So no fancy silhouette deferral is needed! Although i _did_ look into that also... we can talk about framebuffers later... @cwillisf 

### Reason for Changes

_Explain why these changes should be made_

We were using private APIs, and public APIs in unexpected ways, to get the result we wanted from the renderer. Now just use the public APIs in totally expected ways. :) 

### Test Coverage

_Please show how you have added tests to cover your changes_

To test manually, add the video extension and see how adjusting the transparency displays correct colors. Turning transparency up to 100 should make you completely disappear.

### CODE REVIEW

File: src/io/video.js [hunk 1]
```diff
@@ -21,12 +21,6 @@ class Video {
          */
         this._skinId = -1;
 
-        /**
-         * The Scratch Renderer Skin object.
-         * @type {Skin}
-         */
-        this._skin = null;
-
```
Comment (cwillisf) [inline src/io/video.js:29]: 😎

File: src/io/video.js [hunk 2]
```diff
@@ -176,16 +169,17 @@ class Video {
...
-                const canvas = this.getFrame({format: Video.FORMAT_CANVAS});
+                const imageData = this.getFrame({
+                    format: Video.FORMAT_IMAGE_DATA,
+                    cacheTimeout: this.runtime.currentStepTime
+                });
 
-                if (!canvas) {
-                    this._skin.clear();
+                if (!imageData) {
+                    renderer.updateBitmapSkin(this._skinId, new ImageData(...Video.DIMENSIONS), 1);
```
Comment (cwillisf) [inline src/io/video.js:178]: It might be a good idea to cache and reuse this "empty frame" `ImageData` to reduce garbage collection load.

**Review by cwillisf — APPROVED** [review]
I made one suggestion but it's more of a detail; if there's no time to implement the change then I think it's fine to make that a followup later. Otherwise, this looks great! Thanks for digging in and being so thorough!

File: src/io/video.js (hunk 2 above)
Comment (paulkaplan) [reply src/io/video.js:178]: Good point. Done!
