### PR TITLE
Vernier gdxfor tilt values 0 when disconnected

### LINKED ISSUE #1988: Vernier gdxfor tilt values should be 0 when disconnected
### Expected Behavior

Tilt reporter should report 0 when the device is disconnected.

### Actual Behavior

While disconnected, the tilt reporter reports -90 for "front", 90 for "back", etc.

### Steps to Reproduce

- Add the extension but do not connect to a device
- Click the "tilt" reporter

### PR DESCRIPTION
**Pull request by evhan55**
### Resolves

Resolves #1988: Vernier gdxfor tilt values should be 0 when disconnected

### CODE REVIEW

**Comment by ericrosenbaum** [comment]
Thanks! Looks like the comment needs fixing

File: src/extensions/scratch3_gdx_for/index.js [hunk 1]
```diff
@@ -745,6 +745,13 @@ class Scratch3GdxForBlocks {
     }
 
     getTilt (args) {
+        // When the peripheral is not connected, the acceleration magnitude
+        // is 0 instead of ~9.8, which ends up registering a tilt value; so
```
Comment (evhan55) [inline src/extensions/scratch3_gdx_for/index.js]: @ericrosenbaum oh I thought you said the acceleration being 0 ends up affecting the tilt, right? Maybe I misunderstood

Comment (ericrosenbaum) [reply src/extensions/scratch3_gdx_for/index.js]: How about "Tilt values are calculated using acceleration due to gravity, so we need to return 0 when the peripheral is not connected."

Comment (ericrosenbaum) [reply src/extensions/scratch3_gdx_for/index.js]: Good to merge with that fix to the comment- thanks!

**Review by ericrosenbaum — APPROVED** [review]
LGTM!
