### PR TITLE
Prevent "broadcast and wait" being interrupted by a change to its input 

### LINKED ISSUE #2109: "broadcast (expr) and wait" ends if value of (expr) changes
### Expected Behavior

Broadcast and wait block should always wait until its receiver scripts finish.

### Actual Behavior

If the broadcast block contained an expression, changing the value of that expression (e.g. by changing a var it contains) causes the broadcast-and-wait block to end even if its receivers have not yet finished.

### Steps to Reproduce

Create a script along these lines:
`when GF clicked`
`say "hello"`
`set myvar to "test"`
`broadcast (myvar) and wait`
`say "goodbye"`

And a receiver script:
`when I receive "test"`
`wait 1 sec`
`set myvar to "changed"`
`forever {nothing}`

Click GF and note that it says "hello", then 1 sec later says "goodbye" – and yet the receiver script continues to run the forever loop.

Note if you add more work after the "b-a-w" in the first script, it means that *both* scripts are now running simultaneously. Interesting new feature, that...  :D

### Operating System and Browser

Presumably N/A

### PR DESCRIPTION
**Pull request by ericrosenbaum**
### Resolves

Resolves https://github.com/LLK/scratch-vm/issues/2109

### Proposed Changes

Store the input to the "broadcast and wait" block on the stackFrame. While waiting, use the stored value, instead of looking up the argument again. 

### Reason for Changes

Previously, if you used a variable in a "broadcast and wait", and you change the variable's value while it was waiting for the resulting threads to run, the wait would end immediately. This change causes the block to wait until all threads started by it have completed, as in Scratch 2.

### Test Coverage

Added a fixture file to the execute tests

### Credits

Thanks to @apple502j and @adroitwhiz for prior work and investigation
This PR replaces https://github.com/LLK/scratch-vm/pull/2409

### CODE REVIEW

File: src/blocks/scratch3_event.js [hunk 1]
```diff
@@ -90,10 +90,12 @@ class Scratch3EventBlocks {
...
     broadcastAndWait (args, util) {
-        const broadcastVar = util.runtime.getTargetForStage().lookupBroadcastMsg(
-            args.BROADCAST_OPTION.id, args.BROADCAST_OPTION.name);
-        if (broadcastVar) {
-            const broadcastOption = broadcastVar.name;
+        if (!util.stackFrame.broadcastVar) {
+            util.stackFrame.broadcastVar = util.runtime.getTargetForStage().lookupBroadcastMsg(
+                args.BROADCAST_OPTION.id, args.BROADCAST_OPTION.name);
+        }
+        if (util.stackFrame.broadcastVar) {
```
Comment (kchadha) [inline src/blocks/scratch3_event.js:97]: This could just be an `else` to the previous `if`

Comment (adroitwhiz) [reply src/blocks/scratch3_event.js:97]: The first `if` block modifies `util.stackFrame.broadcastVar`, so this condition could evaluate to something different though, right?

Comment (kchadha) [reply src/blocks/scratch3_event.js:97]: Ah yes, you're right! Good catch. I guess it's written in a confusing way. It could be clearer to write the two checks as:

```
if (!util.stackFrame.broadcastVar) {
    // attempt to set it
}

// If we failed to find the broadcast message, exit
if (!util.stackFrame.broadcastVar) return;
```

But for the sake of simplicity of the code change from what we had before, this is fine too.

**Review by kchadha — APPROVED** [review]
LGTM! Thanks @ericrosenbaum, @apple502j, and @adroitwhiz!
