### PR TITLE
Always use English for kitten

### LINKED ISSUE #1858: Kitten 'meow' for Danish, Dutch and Icelandic doesn't sound right.
### Expected Behavior

With the Text-to-Speech extension, using the Kitten voice in Danish, Dutch, and Icelandic, the 'meow' doesn't sound right.

### Actual Behavior

In Danish, the meow sounds more like 'me-u' and feels truncated.
In Dutch, the meow sounds more like 'me-um'.
In Icelandic, the meow sounds more like 'me-uf'.

For an example of how 'meow' is pronounced in Danish, see: https://youtu.be/uxiXcAioZQc?t=5
The Google Translate-version of meows are also pretty good for reference: https://translate.google.com/#view=home&op=translate&sl=auto&tl=da&text=meow

### Steps to Reproduce

1. Load TTS-extension
2. Set voice to Kitten
3. Set language to Danish, Dutch or Icelandic.
4. Say any word

### PR DESCRIPTION
**Pull request by apple502j**
### Resolves
Resolves #1858 

### Proposed Changes
Always uses English for kitten (A pattern)

### Reason for Changes
`meow` sounds strange in some languages, and translating it is impossible with formatMessage.

### CODE REVIEW

File: src/extensions/scratch3_text2speech/index.js [hunk 1]
```diff
@@ -466,11 +467,12 @@ class Scratch3Text2SpeechBlocks {
         // @todo localize this?
```
Comment (joker314) [inline src/extensions/scratch3_text2speech/index.js]: This is probably no longer a TODO?

**Review by joker314 — CHANGES_REQUESTED** [review]

**Review by ericrosenbaum — APPROVED** [review]
😸😸 Looks good to me- thanks @apple502j !
