### PR TITLE
Select the last target instead of the first after deleting

### LINKED ISSUE #294: Deleting a sprite selects the stage
### Expected Behavior

Deleting a sprite should select the next sprite in the sprite list. The stage should only become selected after deleting the last sprite in the sprite list.

### Actual Behavior

Deleting any sprite with in the sprite list results in the stage becoming selected.
deleting-sprite-stage-selected2

### Steps to Reproduce

1. Add some sprites
2. Delete any sprite
3. Stage becomes selected

### Operating System and Browser

Browser: Chrome 57.0.2987.133
OS: macOS 10.11.6

### PR DESCRIPTION
**Pull request by paulkaplan**
### Resolves

_What Github issue does this resolve (please include link)?_
Fixes https://github.com/LLK/scratch-gui/issues/294
### Proposed Changes

_Describe what this Pull Request does_
Prefer selecting the last target instead of the first (the stage). This way it will always try to stay selected on a target. 

### Reason for Changes

_Explain why these changes should be made_
https://github.com/LLK/scratch-gui/issues/294

--- 

@rschamp sorry I know this was assigned to you, but I figured it was just a one liner. Is this what you had in mind?

### CODE REVIEW

**Review by fsih — APPROVED** [review]

**Review by rschamp — CHANGES_REQUESTED** [review]
I would hope to match Scratch 2.0 behavior, which I think will end up being a bit more than a one-liner.  That behavior is to select the sprite before the deleted sprite, or the first sprite if you deleted the first sprite.

Happy to work on this unless you want to revise what you have to behave that way.

**Comment by paulkaplan** [comment]
@rschamp addressed the comments in 9c5d43e

File: src/virtual-machine.js [hunk 1]
```diff
@@ -364,6 +364,8 @@ class VirtualMachine extends EventEmitter {
      */
     deleteSprite (targetId) {
         const target = this.runtime.getTargetById(targetId);
+        const targetIndexBeforeDelete = this.runtime.targets.map(t => t.id).indexOf(target.id);
```
Comment (rschamp) [inline src/virtual-machine.js:367]: Is this different from `this.runtime.targets.indexOf(target)`?
