### PR TITLE
Fix extension hats

### LINKED ISSUE #705: Extension hat blocks not working
### Expected Behavior

Extension blocks that are hats should activate on an edge as expected. 

### Actual Behavior

The Lego WeDo 2.0 extension hats "When distance < 50" and "When tilted any" do not activate.

### Steps to Reproduce

- Load the current extension prototype: https://ericrosenbaum.github.io/scratch-gui/extensions-oct2017/
- Add the Lego WeDo extension
- Connect a Lego WeDo (note that this requires an edit to the Scratch Device Manager config file)
- Make a stack such as "when distance < 50, play sound meow" 
- Note that it does not trigger when the distance drops below 50

### PR DESCRIPTION
**Pull request by cwillisf**
### Resolves

Resolves #705 

### Proposed Changes

These changes make extension hat blocks function. For now they are assumed to be edge-activated, but see #696.

This PR also includes a fix for what seems to be a long-standing issue affecting hats with more than one input. In this situation, the code to collect hat inputs would permanently assign new values to the block's `fields` list, causing problems in the runtime later on. This was a tricky bug to find since the symptom is so distant from the cause; this might be an argument for using `Object.freeze` and similar features.

As a side effect of fixing extension hat blocks I noticed that the WeDo 2.0 `whenDistance` block wasn't scaled correctly, so I fixed that too. I also put in a workaround for #580.

### Reason for Changes

Further progress on extensions & preparation for Monday's playtest.

### CODE REVIEW

File: src/engine/runtime.js [hunk 1]
```diff
@@ -802,13 +805,14 @@ class Runtime extends EventEmitter {
...
             if (Object.keys(hatFields).length === 0) {
+                hatFields = {}; // don't overwrite the block's actual fields list
                 const hatInputs = blocks.getInputs(block);
                 for (const input in hatInputs) {
                     if (!hatInputs.hasOwnProperty(input)) continue;
                     const id = hatInputs[input].block;
                     const inpBlock = blocks.getBlock(id);
                     const fields = blocks.getFields(inpBlock);
-                    hatFields = Object.assign(fields, hatFields);
+                    Object.assign(hatFields, fields);
```
Comment (cwillisf) [inline src/engine/runtime.js:815]: My guess is the original line here was written thinking that it would act like `hatFields = Object.assign({}, fields, hatFields)`. This new code should be equivalent except that it throws away fewer intermediate objects in cases where there are multiple inputs. In my opinion it's also easier to understand: in particular, it's now obvious that `Object.assign` is expected to modify one of the objects.

**Review by ericrosenbaum — APPROVED** [review]
I tip my hat to you sir!
