### PR TITLE
Dont fix small values

### LINKED ISSUE #5512: Say block rounding is inconsistent with Scratch 2
### Expected Behavior
Say (.009/1) says .009 in scratch 2

### Actual Behavior
Say (.009/1) says .01 in scratch 3

### Steps to Reproduce
Use say and divide operator blocks

### Operating System and Browser
All

/cc @kchadha @BryceLTaylor

### PR DESCRIPTION
**Pull request by fsih**
### Resolves
Resolves https://github.com/LLK/scratch-gui/issues/5512

### Proposed Changes
Do not fix say, think, and ask bubbles to 2 decimal points precision if the absolute value is a number less than .01

### Reason for Changes
This matches the behavior in 2.0

/cc @chrisgarrity

### CODE REVIEW

File: src/blocks/scratch3_looks.js [hunk 1]
```diff
@@ -253,7 +253,7 @@ class Scratch3LooksBlocks {
         if (text === '') return text;
 
         // Limit decimal precision to 2 digits.
-        if (typeof text === 'number') {
+        if (typeof text === 'number' && text >= .01) {
```
Comment (adroitwhiz) [inline src/blocks/scratch3_looks.js]:
```suggestion
        if (typeof text === 'number' && Math.abs(text) >= .01) {
```

**Review by ericrosenbaum — APPROVED** [review]
LGTM!
