### PR TITLE
Fix video motion in Safari/Firefox

### LINKED ISSUE #1055: Video IO device does not work with Safari/Firefox
### Expected Behavior

_Please describe what should happen_

### Actual Behavior

_Describe what actually happens_

Both browsers have deprecated `navigator.getUserMedia` with callbacks, now preferring `navigator.mediaDevices.getUserMedia` with promises.

The GUI uses this package to normalize the promise/callback and gum/media devices.gum behavior.
https://www.npmjs.com/package/get-user-media-promise

The audio engine seems to just use `navigator.mediaDevices.getUserMedia() => promise`, so maybe just changing to that is good enough.

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

Try using video motion on browsers described below

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

Mac + firefox 59, Mac + safari 11.1

### PR DESCRIPTION
**Pull request by paulkaplan**
### Resolves

_What Github issue does this resolve (please include link)?_

Fixes https://github.com/LLK/scratch-vm/issues/1055

### Proposed Changes

_Describe what this Pull Request does_

Most of the diff is actually just an indentation change, so just look for these three things.

1. Use the new `mediaDevices` API the same way the loudness block does.
2. Use `srcObject`, falling back to `createObjectURL`
3. Call `video.play` to start video on Safari/Firefox when using `srcObject`
3. Fix bug with ArrayBuffer.slice() with no params throwing in Safari.

### Reason for Changes

_Explain why these changes should be made_

Fix browser compatibility for video motion!

### Test Coverage

_Please show how you have added tests to cover your changes_

### CODE REVIEW

File: src/io/video.js [hunk 1]
```diff
@@ -240,23 +240,28 @@ class Video {
...
+                } catch (error) {
+                    this._video.src = window.URL.createObjectURL(stream);
+                }
+                this._video.play();
                 // Hint to the stream that it should load. A standard way to do this
                 // is add the video tag to the DOM. Since this extension wants to
                 // hide the video tag and instead render a sample of the stream into
                 // the webgl rendered Scratch canvas, another hint like this one is
                 // needed.
+                this._video.play(); // Needed for Safari/Firefox, Chrome auto-plays.
```
Comment (rschamp) [inline src/io/video.js:263]: Did you play() twice intentionally?

**Comment by paulkaplan** [comment]
NOPE. fixed.

**Comment by paulkaplan** [comment]
Also confirmed functioning on iPad/Safari.
