### PR TITLE
VM changes for the sensing_of block.

### LINKED ISSUE #1762: Sensing of block will evaluate a list in the first menu.
This isn't quite an issue yet, but it is about to be once #1425 and https://github.com/LLK/scratch-gui/issues/2389 are fixed.

The problem is this code doesn't check the variable types and it probably should:
https://github.com/LLK/scratch-vm/blob/develop/src/blocks/scratch3_sensing.js#L316

### Expected Behavior

Variables should show up in the first menu of the sensing of block (they don't yet, but I'm working on it #1425). Once I add them, you can get a list in there and it will also evaluate:
screen shot 2018-11-14 at 7 11 14 pm

### Steps to Reproduce

Getting the list in their is slightly convoluted:
1. make a project with 2 sprites
2. in sprite one add variable 'pizza'
3. in sprite 2, drag out a sensing of block to the workspace
4. select sprite 1 in the right menu
5. select the variable 'pizza' in the first sensing block menu
6. Go back to sprite 1 and add a list 'pizza'. Add some items to the list.
7. Remove the variable 'pizza'
8. Go back to Sprite 2 and click on the sensing block. (which should still have pizza selected)

In scratch 2 this evaluates to 0 (though the steps to get the list selected are slightly different)

### LINKED ISSUE #2389: ___ of ___ block should not have backdrop # or backdrop name options
### Expected Behavior

The `___ of ____` sensing block should not have `backdrop #` or `backdrop name` options in the dropdown and match scratch 2.0

### Actual Behavior

It has those extra options
screen shot 2018-06-18 at 4 45 25 pm

### Steps to Reproduce

Choose Sensing from the Category Menu
Locate the ___ of ___ block (starts as X position of Stage)
Select the first dropdown on the selected block
Note: it has `backdrop #` and `backdrop name` as options

### Operating System and Browser

Chrome on Mac

### LINKED ISSUE #2390: ___ of ___ sensing block should have different options for stage
### Expected Behavior

If the stage is selected in the second drop down of the ___ of ___ sensing block, the first drop down should not show `x position`, `y position`, `direction`, `costume #`, `costume name`, or `size`

### Actual Behavior

All of those options appear
screen shot 2018-06-18 at 5 05 41 pm

### Steps to Reproduce

Set the ___ of ___ sensing block to the stage
Click on the first drop down

### Operating System and Browser

Chrome on Mac

### PR DESCRIPTION
**Pull request by picklesrus**
### Resolves

Resolves #1762 and resolves LLK/scratch-gui#2389 and resolves LLK/scratch-gui#2390.

### Proposed Changes

This handles lists properly (by ignoring them like Scratch2 and makes the attribute menu update based on what was chosen in the target menu.

Comments from this PR are all in https://github.com/LLK/scratch-vm/pull/1774 which github seems to now think includes far more than it actually does.

### CODE REVIEW

File: src/engine/blocks.js [hunk 1]
```diff
@@ -567,6 +567,16 @@ class Blocks {
                 if (!optRuntime){
                     break;
                 }
+                // The selected item in the sensing of block menu needs to change based on the
+                // selected target.  Set it to the first item in the menu list.
```
Comment (kchadha) [inline src/engine/blocks.js:571]: Do you mind filing a tech debt issue and then referencing it here via `// TODO (#<issue>)`

Comment (kchadha) [reply src/engine/blocks.js:571]: (The one that we talked about in the original PR)

File: test/unit/blocks_sensing.js [hunk 2]
```diff
@@ -5,6 +5,7 @@ const Sprite = require('../../src/sprites/sprite');
 const RenderedTarget = require('../../src/sprites/rendered-target');
 const BlockUtility = require('../../src/engine/block-utility');
 
+
```
Comment (kchadha) [inline test/unit/blocks_sensing.js]: Stray newline.

**Review by kchadha — COMMENTED** [review]
Some minor nits and then LG!

**Comment by picklesrus** [comment]
Fixed. Sorry for all of the back and forth and multiple PRs and everything on this one :-/

**Review by kchadha — APPROVED** [review]
LGTM! Thanks for all the work on this one!
