### PR TITLE
Make duplicateVariable deep copy the array instead of keeping reference.

### LINKED ISSUE #1798: Clones inherit "For this sprite only" list
### Expected Behavior
Like variables are, "for this sprite only" lists should be independent on each clone.

### Actual Behavior
They share the same list.

### Steps to Reproduce
I made a simple project to test it. 
image
[LocalListBug.zip](https://github.com/LLK/scratch-vm/files/2638846/LocalListBug.zip)
(This is a sb3 file. Change extension to `sb3`. )
Press space key. On Scratch 2.0, the parent always says "0".
On Scratch 3.0, both the parent and the clone say the same number.

### Operating System and Browser
Windows 7 / Firefox 63

Thanks to videobob for [finding this strange bug](https://scratch.mit.edu/discuss/post/3333723/)!

### PR DESCRIPTION
**Pull request by paulkaplan**
### Resolves

_What Github issue does this resolve (please include link)?_

Fixes https://github.com/LLK/scratch-vm/issues/1798

### Proposed Changes

_Describe what this Pull Request does_

Make duplicateVariable deep copy the array instead of keeping reference.

### Reason for Changes

_Explain why these changes should be made_

Previously it looked like clones were sharing private lists, but it was actually just a bug in the way the values were copied while duplicating

### Test Coverage

_Please show how you have added tests to cover your changes_

Added unit test

### CODE REVIEW

File: test/unit/engine_target.js [hunk 1]
```diff
@@ -323,6 +323,18 @@ test('duplicateVariable creates a new variable with a new ID by default', t => {
     t.end();
 });
 
+test('duplicateVariable creates new array reference for list variable.value', t => {
+    const target = new Target();
+    const arr = [1, 2, 3];
+    target.createVariable('a var ID', arr, Variable.LIST_TYPE);
```
Comment (kchadha) [inline test/unit/engine_target.js]: Hmmm not sure what's happening here but the second argument to `createVariable` should be a string not an array..

Comment (kchadha) [reply test/unit/engine_target.js]:
```suggestion
    target.createVariable('a var ID', 'arr', Variable.LIST_TYPE);
```

File: test/unit/engine_target.js [hunk 2]
```diff
@@ -323,6 +323,18 @@ test('duplicateVariable creates a new variable with a new ID by default', t => {
...
+    const originalVariable = target.variables['a var ID'];
```
Comment (kchadha) [inline test/unit/engine_target.js:330]:
```suggestion
    const originalVariable = target.variables['a var ID'];
    originalVariable.value = arr;
```

**Review by kchadha — COMMENTED** [review]
The unit test has a typo and a missing value setting line. LG after that.
