### PR TITLE
Fix importing hidden monitors from Scratch 2 projects

### LINKED ISSUE #1165: Variable monitors do not import correctly if they are initially hidden
### Expected Behavior

All variable monitors should import in their correct position and mode (normal/large/slider). The example project (after the "show 4-6" button is clicked) should look like this:

Screenshot of project in 2.0

### Actual Behavior

Variable monitors which are hidden when the 2.0 project is saved do not import with their position or mode. When shown (via the palette checkbox or a "show variable" block), they all line up at the top left, the default position for variable monitors, and are in normal-readout mode (with the min/max values for the slider the default 0-100). The example project (again, after "show 4-6" is pressed) looks like this:

Screenshot of project in 3.0

### Steps to Reproduce

Create a Scratch 2.0 project and place a variable in any position or mode, then hide the variable. Save the project and open it in Scratch 3.0, then show the variable. Note that the variable is in the top left of the stage and the default/normal mode instead of however it was positioned/set.

My example project: https://scratch.mit.edu/projects/225201357/ ([3.0](https://llk.github.io/scratch-gui/develop/#225201357))

Many projects which use variables as part of the user interface are affected by this issue. I stumbled across this issue [here (warning, this project has many assets)](https://scratch.mit.edu/projects/172355986/).

### Operating System and Browser

Issue exists on both Firefox 61.0b7 and Chromium 62.0.3202.89, running Debian (testing).

### PR DESCRIPTION
**Pull request by hyperobject**
### Resolves
This PR fixes #1165, and addresses some of llk/scratch-gui#2033.

### Proposed Changes
* Changes to the `changeBlock` function in blocks.js to add monitors with additional relevant parameters (x, y, mode, sliderMin, sliderMax) so shown monitors are created with those parameters
* Changes to the behavior of `requestRemoveMonitor` so it sets the `visible` parameter to false instead of deleting monitor state on remove
* Changes to how `requestAddMonitor` and `requestChangeMonitor` merge in a passes object
   * The `merge` function allows undefined objects to overwrite keys that already have a defined value, so I changed it to `mergeWith` and some extra logic to handle undefined or null values.

### Potential Gotchas
Monitor position is handled in scratch-gui, so there might be some weird interactions with the logic added here in edge cases. I wasn't able to find any examples of this, though.

### CODE REVIEW

**Comment by kchadha** [comment]
@paulkaplan also added you to this, for sanity checking =D

File: src/engine/runtime.js [hunk 1]
```diff
@@ -1522,7 +1522,18 @@ class Runtime extends EventEmitter {
      * @param {!MonitorRecord} monitor Monitor to add.
      */
     requestAddMonitor (monitor) {
-        this._monitorState = this._monitorState.set(monitor.get('id'), monitor);
+        const id = monitor.get('id');
+        if (this._monitorState.has(id)) {
```
Comment (kchadha) [inline src/engine/runtime.js]: Maybe you can just use `requestUpdateMonitor` here instead of defining the functionality twice. `requestUpdateMonitor` can return a boolean representing whether a monitor already existed in the state, and then if it didn't, you can set it here as in the else case below.

**Review by kchadha — APPROVED** [review]
LGTM!

**Review by kchadha — CHANGES_REQUESTED** [review]
Blocks don't have some of the properties you're referencing in the 'checkbox' case for the changeBlock function. Maybe we should try to repro the case we talked about offline.

File: src/engine/blocks.js [hunk 2]
```diff
@@ -529,18 +529,21 @@ class Blocks {
...
+                if (!optRuntime.requestShowMonitor(block.id)) {
+                    optRuntime.requestAddMonitor(MonitorRecord({
+                        id: block.id,
+                        targetId: block.targetId,
+                        spriteName: block.targetId ? optRuntime.getTargetById(block.targetId).getName() : null,
+                        opcode: block.opcode,
+                        params: this._getBlockParams(block),
+                        // @todo(vm#565) for numerical values with decimals, some countries use comma
+                        value: '',
+                        mode: block.opcode === 'data_listcontents' ? 'list' : block.mode
```
Comment (kchadha) [inline src/engine/blocks.js]: `block.mode` here should go back to being `default` since `block.mode` doesn't exist.

File: src/engine/runtime.js [hunk 3]
```diff
@@ -1522,24 +1522,37 @@ class Runtime extends EventEmitter {
      * @param {!MonitorRecord} monitor Monitor to add.
```
Comment (kchadha) [inline src/engine/runtime.js:1522]: This comment should be updated to replace 'overwrites it.' with something like: 'updates those properties that are defined in the given monitor record.'

File: src/engine/runtime.js [hunk 4]
```diff
@@ -1522,24 +1522,37 @@ class Runtime extends EventEmitter {
...
+                        return prev;
+                    }
+                    return next;
+                }, monitor));
+            return true;
         }
+        return false;
     }
-
+
```
Comment (kchadha) [inline src/engine/runtime.js]: stray whitespace (indent) added here

File: src/engine/runtime.js [hunk 5]
```diff
@@ -1549,6 +1562,32 @@ class Runtime extends EventEmitter {
         this._monitorState = this._monitorState.delete(monitorId);
     }
 
+    /**
+     * Hides a monitor. Does nothing if the monitor already does
```
Comment (kchadha) [inline src/engine/runtime.js]: Replace 'Does nothing' with 'Returns false'

File: src/engine/runtime.js [hunk 6]
```diff
@@ -1522,24 +1522,37 @@ class Runtime extends EventEmitter {
...
+        const id = monitor.get('id');
+        if (!this.requestUpdateMonitor(monitor)) { // update monitor if it exists in the state
+            // if the monitor did not exist in the state, add it
+            this._monitorState = this._monitorState.set(id, monitor);
+        }
     }
 
     /**
-     * Update a monitor in the state. Does nothing if the monitor does not already
+     * Update a monitor in the state. Does nothing and returns false if the monitor does not already
```
Comment (kchadha) [inline src/engine/runtime.js]: Maybe replace this description with: 'Update a monitor in the state and report its success/failure.'

File: src/engine/runtime.js (hunk 5 above)
Comment (kchadha) [reply src/engine/runtime.js]: JK -- new suggestion (same as above):
> Maybe replace this description with: 'Update a monitor in the state and report its success/failure.'

File: src/engine/runtime.js [hunk 7]
```diff
@@ -1549,6 +1562,32 @@ class Runtime extends EventEmitter {
         this._monitorState = this._monitorState.delete(monitorId);
     }
 
+    /**
+     * Hides a monitor. Does nothing if the monitor already does
+     * not exist in the state.
+     * @param {!string} monitorId ID of the monitor to remove.
```
Comment (kchadha) [inline src/engine/runtime.js]: 'remove' -> 'hide'

File: src/engine/runtime.js [hunk 8]
```diff
@@ -1549,6 +1562,32 @@ class Runtime extends EventEmitter {
...
+        return this.requestUpdateMonitor(new Map([
+            ['id', monitorId],
+            ['visible', false]
+        ]));
+    }
+
+    /**
+     * Shows a monitor. Does nothing if the monitor already does
+     * not exist in the state.
+     * @param {!string} monitorId ID of the monitor to remove.
```
Comment (kchadha) [inline src/engine/runtime.js]: 'remove' -> 'show'

Comment (kchadha) [reply src/engine/runtime.js]: Also same comment as above re: 'Does nothing...'

**Review by kchadha — CHANGES_REQUESTED** [review]
Just had some last few minor comments!

**Review by kchadha — APPROVED** [review]
LGTM
