### PR TITLE
Round (x position) and (y position) to 8 places

### LINKED ISSUE #1150: (x position) is more precise than in 2.0
### Expected Behavior

For perfect compatibility, `(x position)` should round to 8 decimal places

### Actual Behavior

It looks like `(x position)`  is rounding to 16 decimal places

### Steps to Reproduce

https://llk.github.io/scratch-gui/develop/compatibility-testing.html#223591096

This project breaks in 3.0: https://llk.github.io/scratch-gui/develop/#117386152/

### Operating System and Browser

MacOS 10.12.4, Chrome 66.0.3359.139 (64-bit)

### PR DESCRIPTION
**Pull request by Kenny2github**
### Resolves

Fixes #1150 

### Proposed Changes

Adds a `round_coord` function as a quick and easy shortcut to rounding to N digits, then uses that in `getX` and `getY` to round the coordinates to 8 decimal places at most.

### Reason for Changes

To fix a help wanted issue

### CODE REVIEW

File: src/blocks/scratch3_motion.js [hunk 1]
```diff
@@ -258,12 +258,16 @@ class Scratch3MotionBlocks {
         util.target.setXY(util.target.x, y);
     }
 
+    roundCoord (value, places) {
+        return Math.round(value * Math.pow(10, places)) / Math.pow(10, places);
+    }
+
     getX (args, util) {
-        return util.target.x;
+        return this.roundCoord(util.target.x, 8);
```
Comment (mzgoddard) [inline src/blocks/scratch3_motion.js]: Applying this on get would fix projects that use setX. The precision would not be bound if you are using changeXBy command blocks. Should this rather be done in target's setXY so the stored value is the correct precision instead of the temporary value returned from getX?

Comment (mzgoddard) [reply src/blocks/scratch3_motion.js]: I think the concern of truncating is better placed in Target than in the command blocks.

Comment (mzgoddard) [reply src/blocks/scratch3_motion.js]: What I mean by changeXBy not being affected is you could have multiple changeXBy operations that change by more precision that getX returns.

I'm not fully sure my comments here are helpful.

File: src/blocks/scratch3_motion.js [hunk 2]
```diff
@@ -258,12 +258,16 @@ class Scratch3MotionBlocks {
         util.target.setXY(util.target.x, y);
     }
 
+    roundCoord (value, places) {
+        return Math.round(value * Math.pow(10, places)) / Math.pow(10, places);
```
Comment (mzgoddard) [inline src/blocks/scratch3_motion.js]: Using a constant variable in place of the Math.pow calls I think would perform better and let the constant names better describe why the rounding is needed? Does that seem fair?

**Review by mzgoddard — COMMENTED** [review]
Hope these help.

File: src/blocks/scratch3_motion.js (hunk 1 above)
Comment (Kenny2github) [reply src/blocks/scratch3_motion.js]: I get what you mean, but I'm not sure where the code for `util.target` is 😛

Comment (Kenny2github) [reply src/blocks/scratch3_motion.js]: Ah, found it.

**Comment by Kenny2github** [comment]
Note: rebased and force pushed to clean up stupid mistakes

**Comment by mrjacobbloom** [comment]
Should this only apply in compatibility mode? it makes more sense to me that in 3.0 for everything should use the same 64-bit precision (and avoid a few math operations if it matters)

**Review by rschamp — APPROVED** [review]
Thanks @Kenny2github! And @mzgoddard for your review. Looks/works great.

**Comment by rschamp** [comment]
@mrjacobbloom Unfortunately "compatibility mode" has lost some of its meaning, as we aren't planning to conditionally apply that flag any time soon.
