### PR TITLE
Localize the Text to Speech extension "set language" menu

### LINKED ISSUE #1673: "Set language" menu in Text to Speech extension should accept dropped language names
### Expected Behavior

In the Text to Speech extension, the `set language` block should let you drop a block that reports a language name onto it. This should work for language names in any language. For example, you should be able to use the “language” reporter from the Translate extension to set the Text to Speech language.

### Actual Behavior

Dropped arguments in the `set language` block are generally ignored (technically right now you can drop in scratch locale codes, but that's not how it should work!).

### LINKED ISSUE #1678: Translate languages for Set language block (TTS Extension)
### Expected Behavior
Language names should be in Japanese when I use Scratch in Japanese.

### Actual Behavior
It says "Japanese" instead of "日本語".

### Steps to Reproduce
1. Load TTS Extension
2. Set the language to japanese

### Operating System and Browser
On Windows 10 Firefox 62

### PR DESCRIPTION
**Pull request by ericrosenbaum**
### Resolves

Resolves https://github.com/LLK/scratch-vm/issues/1678
Resolves https://github.com/LLK/scratch-vm/issues/1673

Depends on https://github.com/LLK/scratch-translate-extension-languages/pull/12

### Proposed Changes

In the Text to Speech extension, use the translated language names from the `scratch-translate-extension-languages` module to display a localized menu of language names in the "set language" block.  

Note that this change depends on an update to the `scratch-translate-extension-languages` module that includes translations of some spoken language names.

Screen Shot 2019-10-03 at 4 26 09 PM
Screen Shot 2019-10-03 at 4 26 30 PM

Also, support dropped arguments in the "set language" block, so that a language could be selected using a string that is a language name (in any language). This works with the translate extension's "language" reporter block, so you can now create projects that translate into and then speak in whatever language the editor is currently set to:

Screen Shot 2019-10-03 at 4 31 24 PM
Screen Shot 2019-10-03 at 4 31 07 PM

### CODE REVIEW

File: src/extensions/scratch3_text2speech/index.js [hunk 1]
```diff
@@ -584,14 +595,44 @@ class Scratch3Text2SpeechBlocks {
...
+        let nameArray = languageNames.menuMap[editorLanguage];
+        if (nameArray) {
+            // Also get any localized names of spoken languages
+            let spokenNameArray = [];
+            if (languageNames.spokenLanguages) {
+                spokenNameArray = languageNames.spokenLanguages[editorLanguage];
+                nameArray = nameArray.concat(spokenNameArray);
+            }
+            // Create a map of language code to localized name
+            nameArray.forEach(lang => {
```
Comment (picklesrus) [inline src/extensions/scratch3_text2speech/index.js:623]: Maybe add a note about how we don't end up with duplicates for Chinese and Mandarin in the array.

Comment (picklesrus) [reply src/extensions/scratch3_text2speech/index.js:623]: And a test for it :)

Comment (ericrosenbaum) [reply src/extensions/scratch3_text2speech/index.js:623]: all set!

**Comment by ericrosenbaum** [comment]
(tests will fail until we update the scratch-translate-extension-languages module)
