### PR TITLE
BOOST color sensing fixes

### LINKED ISSUE #2090: BOOST extension: color names should be localized
### Expected Behavior

All text presented by an extension to the user should be localized.

### Actual Behavior

Looks like the color names used by the color reporter are not localized.

### LINKED ISSUE #2112: BOOST extension: using multiple "when color any" hats does not work
### Expected Behavior

It should be possible to use the "when color seen" hat with the "any" option selected in two different stacks at the same time.

### Actual Behavior

If you make two stacks started by "when color any", only one of them will start when the color changes:

Screen Shot 2019-04-11 at 1 29 01 PM

### LINKED ISSUE #2113: BOOST extension: "when color any" hat does not trigger twice in a row for the same color
### Expected Behavior

It should be possible to show the color sensor any sequence of colors, and have the "when color any" hat trigger on each transition between two colors, or between "none" and a color.

### Actual Behavior

If you show the sensor something red, then take it away, then show it again, it triggers the first time, but not the second time.

I noticed that the hat opcode is returning "undefined" most of the time, and only occasionally `true` or `false`, which is probably related to this bug.  Edge-triggered hat opcodes should always return either true or false.

### LINKED ISSUE #2114: BOOST extension: color reporter design?
Currently the BOOST extension includes a "color" reporter, which reports a string which is the name of the color the sensor currently sees, such as "red", "yellow", or "none".

If we keep this approach, we'll need to localize these color names. Then the problem would be that if I create code that checks value of the reporter, it will work for me but not for people using the editor in other languages:

Screen Shot 2019-04-11 at 1 43 22 PM

For example, if I load this project with the editor set to Spanish, the reporter will report "rojo" instead of "red", and the condition will never be true.

So, we might consider instead creating a boolean reporter block with a menu listing the color names- something like:

<seeing color [red]?>

This would allow you to do the same thing as above, but more simply, in a way that works across languages. 

If we replace the color string reporter with the boolean, though, we will lose the ability to live monitor the color sensor's value, which is very useful.

### PR DESCRIPTION
**Pull request by ericrosenbaum**
### Resolves

resolves https://github.com/LLK/scratch-vm/issues/2114
resolves https://github.com/LLK/scratch-vm/issues/2113
resolves https://github.com/LLK/scratch-vm/issues/2112
resolves https://github.com/LLK/scratch-vm/issues/2090

### Proposed Changes

This is a set of related fixes and changes to the BOOST extension color sensing blocks:

- Remove the `color` string reporter (which also removes the need to localize that reporter's output)
- Add a boolean reporter: `<seeing [any color] brick?>`
- Change the wording on the hat block to: `when [any color] brick seen`
- Clean up the hat block functionality by using a new system to refer to colors internally. Previously we were using a combination of ids (which were also used as UI strings) and numeric indices (which are sent from the hub). This change uses a single set of IDs to represent color: as menu values, where sensor values are stored, and in opcodes when comparing colors. The conversion from index to ID is done in just one place, when the BLE message arrives. 
- Fix the ability for multiple "when color any" hats to trigger, by moving where `previousColor` is set out of the opcode function   

### Questions

The `BoostColorIdByIndex` object may not be the cleanest solution for looking up a color id by index. Maybe this should be some other data structure? Or a function with a switch statement?

### CODE REVIEW

**Comment by evhan55** [comment]
Testing this now for functionality:

- #2114: the new `seeing [color] brick?` boolean reporter works well for me!
- #2113: `when [any color] brick seen` hat triggers twice in a row for the same color
- #2112: two `when [any color] brick seen` hats trigger at the same time
- #2090: color names in menus seem localized in the code, now

The tester project sent to me by @ericrosenbaum works really great!  This PR seems to significantly improve the color sensing functionality in the Boost extension, and makes it feel very usable.

I will look at the code and give comments separately.

File: src/extensions/scratch3_boost/index.js [hunk 1]
```diff
@@ -101,18 +101,30 @@ const BoostPort = {
 };
 
 /**
- * Enum for indexed colors read by the Boost Vision Sensor
+ * Ids for each color sensed by the Boost Vision Sensor
+ */
+const COLOR_ID_ANY = 'any';
```
Comment (evhan55) [inline src/extensions/scratch3_boost/index.js]: I tried to simplify this by not needing the extra color ID values and wasn't successful at finding a better alternative.  However, I wonder if these could get renamed to `COLOR_ANY` and `COLOR_RED` etc, for a bit of simplification?

File: src/extensions/scratch3_boost/index.js [hunk 2]
```diff
@@ -101,18 +101,30 @@ const BoostPort = {
...
  */
-const BoostColor = {
-    NONE: 255,
-    RED: 9,
-    BLUE: 3,
-    GREEN: 5,
-    YELLOW: 7,
-    WHITE: 10,
-    BLACK: 0
+const BoostColorIdByIndex = {
```
Comment (evhan55) [inline src/extensions/scratch3_boost/index.js]: This could probably stay named `BoostColor`, also for the sake of a simpler name, just a thought!

**Review by evhan55 — APPROVED** [review]
lgtm!

**Comment by evhan55** [comment]
The new data structures are still working for me and read more clearly!

**Review by evhan55 — APPROVED** [review]
lgtm!
