### PR TITLE
Consistently format text bubbles

### LINKED ISSUE #2186: "Say" and "Think" bubbles have different numeric precision
### Expected Behavior

"Say" and "Think" bubbles should display the same output when given the same input, with the only difference being the shape of the bubble.

### Actual Behavior

~While visions of floating-point precision errors drift through Scratch Cat's thoughts, he is too shy to vocalize them~
"Say" bubbles are limited to 2 decimal digits of numeric precision, but "think" bubbles are not:
image

### Steps to Reproduce

1. Make a sprite "say" a number with more than 2 digits of precision
2. Make the sprite "think" the number

(Or see [this project](https://scratch.mit.edu/projects/313667447/editor/))

### PR DESCRIPTION
**Pull request by adroitwhiz**
### Resolves

Resolves #2186 

### Proposed Changes

This adds a new private function, `_formatBubbleText`, to `Scratch3LooksBlocks`. This function, which formats the bubble's text by clamping decimal precision to 2 digits and limiting its length, is called by `_updateBubble`, which is in turn called by all functions which change text bubble state.

This formatting was previously done by the `say` and `think` functions. However, only the `say` function limited decimal precision, making speech bubbles and thinking bubbles inconsistent.

This does introduce a minor compatibility change from 2.0: "ask" bubbles' decimal precision is now limited as well, whereas it was not limited in 2.0.

Another minor (non-compatibility) change: `say` emitted a `SAY` event, while `think` called `_updateBubble` directly. Now, both emit a `SAY` event.

### Reason for Changes

These changes, in addition to fixing one current bug, reduce code duplication and potential for future bugs.

### Test Coverage

I have modified the `blocks_looks` unit test to check the "think" block's rounding, and to check the string from the bubble as displayed instead of from the `SAY` event.

- Should the `SAY` event's text come already formatted? I don't believe it should, which is why I changed the test, but I want your opinion(s).

### CODE REVIEW

**Comment by adroitwhiz** [comment]
@paulkaplan Mind taking a look at this when you get the chance?

File: src/blocks/scratch3_looks.js [hunk 1]
```diff
@@ -325,7 +340,7 @@ class Scratch3LooksBlocks {
     }
 
     think (args, util) {
-        this._updateBubble(util.target, 'think', String(args.MESSAGE).substr(0, Scratch3LooksBlocks.SAY_BUBBLE_LIMIT));
+        this.runtime.emit('SAY', util.target, 'think', args.MESSAGE);
```
Comment (fsih) [inline src/blocks/scratch3_looks.js]: Can we change 'SAY' to a constant variable and rename it to 'SAY_OR_THINK'?

**Review by fsih — APPROVED** [review]
Looks good besides one nit!

File: src/blocks/scratch3_looks.js (hunk 1 above)
Comment (adroitwhiz) [reply src/blocks/scratch3_looks.js]: As a static getter on `Runtime`, on `Scratch3LooksBlocks`, or just as a `const` at the top of the file?

Comment (fsih) [reply src/blocks/scratch3_looks.js]: I think static getter on Scratch3LooksBlocks

Comment (adroitwhiz) [reply src/blocks/scratch3_looks.js]: Hopefully [this](https://github.com/LLK/scratch-vm/pull/2187/commits/ffd2a2a9e8f7a95df6bd81d60fe1457fcb4a1918) is good. There are a lot of places in the codebase that still use the raw event string `'SAY'` as the event name, but the codebase also uses raw event strings for many other event listeners as well, so I opted against changing all of the `'SAY'` listeners over to `Scratch3LooksBlocks.SAY_OR_THINK`.

Even if I did rename all the `'SAY'` events in this codebase to `'SAY_OR_THINK'` (the string), `scratch-render`'s tests use `'SAY'` events as well, so those would need to be changed simultaneously to prevent breakage.
