### PR TITLE
Fix sprite rename incrementing when renamed to itself

### LINKED ISSUE #370: Sprite names handle numbers incorrectly
### Expected Behavior

Entering a sprite name of "sprite_1" changes sprite name to "sprite_1".
Names can be arbitrary strings of letters, numbers, and allowed special characters. 

### Actual Behavior

Entering a sprite name of "sprite_1" changes sprite name to "sprite_2".
Entering the name "sprite_2" changes sprite name to "sprite_3".
Entering "sprite_4" changes sprite name to "sprite_2".
Entering "sprite_999" changes sprite name to "sprite_2".

The number 2 is automatically appended to any letters entered; "hello" becomes "hello2".

Every number but 2 is changed to 2, except for 2 itself, which becomes 3 when a user enters a string ending in a single 2 as a new sprite name. Entering "sprite_2" when a sprite name is already "sprite_2" has no effect. 

### Steps to Reproduce

Enter any string into the name field of a sprite, and it follows this pattern. 

### Operating System and Browser

Ubuntu 16.04.1, Firefox 53.0 (64-bit)
Windows 10, Firefox 53.0.2 (32-bit)

### PR DESCRIPTION
**Pull request by paulkaplan**
### Resolves

_What Github issue does this resolve (please include link)?_
Resolves https://github.com/LLK/scratch-gui/issues/370

### Proposed Changes

_Describe what this Pull Request does_
Filter out your own sprite name when creating the list of names to consider "used" when renaming. 

### Reason for Changes

_Explain why these changes should be made_
See comment on https://github.com/LLK/scratch-gui/issues/370
### Test Coverage

_Please show how you have added tests to cover your changes_
Added a test for this case.

### CODE REVIEW

File: src/virtual-machine.js [hunk 1]
```diff
@@ -329,9 +329,8 @@ class VirtualMachine extends EventEmitter {
             }
             if (newName && RESERVED_NAMES.indexOf(newName) === -1) {
                 const names = this.runtime.targets
-                    .filter(runtimeTarget => runtimeTarget.isSprite())
+                    .filter(runtimeTarget => runtimeTarget.isSprite() && runtimeTarget.id !== target.id)
                     .map(runtimeTarget => runtimeTarget.sprite.name);
-
                 sprite.name = StringUtil.unusedName(newName, names);
```
Comment (fsih) [inline src/virtual-machine.js:334]: Another weird thing about thing about this bug was

"Every number but 2 is changed to 2, except for 2 itself, which becomes 3 when a user enters a string ending in a single 2 as a new sprite name."

Not needed for this fix, but is it weird that when you try to name two sprites TurboBlaster9000, the second one gets renamed to TurboBlaster2? Maybe it would make more sense to go to TurboBlaster9001 or TurboBlaster9000_2?

File: src/virtual-machine.js [hunk 2]
```diff
@@ -329,9 +329,8 @@ class VirtualMachine extends EventEmitter {
             }
             if (newName && RESERVED_NAMES.indexOf(newName) === -1) {
```
Comment (fsih) [inline src/virtual-machine.js:330]: Should we find where this is firing twice and remove the second time?

Comment (paulkaplan) [reply src/virtual-machine.js:330]: It is coming from the GUI, so wouldn't be part of this fix.

File: src/virtual-machine.js (hunk 1 above)
Comment (paulkaplan) [reply src/virtual-machine.js:334]: Yeah @rschamp and I discussed that. Since it is currently the way scratch2 works, we decided to leave it that way for now.

**Review by fsih — APPROVED** [review]
