### PR TITLE
Consistently format text bubbles (this time, like 2.0 does)

### LINKED ISSUE #2186: "Say" and "Think" bubbles have different numeric precision
### Expected Behavior

"Say" and "Think" bubbles should display the same output when given the same input, with the only difference being the shape of the bubble.

### Actual Behavior

~While visions of floating-point precision errors drift through Scratch Cat's thoughts, he is too shy to vocalize them~
"Say" bubbles are limited to 2 decimal digits of numeric precision, but "think" bubbles are not:
image

### Steps to Reproduce

1. Make a sprite "say" a number with more than 2 digits of precision
2. Make the sprite "think" the number

(Or see [this project](https://scratch.mit.edu/projects/313667447/editor/))

### PR DESCRIPTION
**Pull request by adroitwhiz**
### Resolves

Resolves #2186

### Proposed Changes

This PR does mostly the same thing as https://github.com/LLK/scratch-vm/pull/2187, but matches 2.0's behavior of always rounding to 2 decimal places even if the number only needs 1 decimal place.

### Reason for Changes

These changes, in addition to fixing one current bug, reduce code duplication and potential for future bugs.

### Test Coverage

Yes

### CODE REVIEW

File: src/blocks/scratch3_looks.js [hunk 1]
```diff
@@ -233,6 +243,30 @@ class Scratch3LooksBlocks {
...
+    _formatBubbleText (text) {
+        if (text === '') return text;
+
+        // Non-integers should be rounded to 2 decimal places (no more, no less), unless they're small enough that
+        // rounding would display them as 0.00. This matches 2.0's behavior:
+        // https://github.com/LLK/scratch-flash/blob/2e4a402ceb205a042887f54b26eebe1c2e6da6c0/src/scratch/ScratchSprite.as#L579-L585
+        if (typeof text === 'number' &&
+            Math.abs(text) >= 0.01 && text % 1 !== 0) {
+            text = text.toFixed(2);
+
```
Comment (fsih) [inline src/blocks/scratch3_looks.js]: Extra newline?

**Review by fsih — APPROVED** [review]
Thanks for your patience with us figuring out what behavior we wanted. LG!
